-- 1
SELECT USERID
FROM S_EMP
WHERE ID = 23;

-- 2
SELECT LAST_NAME || FIRST_NAME AS EMPLOYEES, S_DEPT.ID
FROM S_DEPT INNER JOIN S_EMP ON S_DEPT.ID = S_EMP.DEPT_ID
WHERE S_DEPT.ID = 10 OR S_DEPT.ID = 50
ORDER BY LAST_NAME ASC;

-- 3
SELECT ID, LAST_NAME,FIRST_NAME
FROM S_EMP
WHERE LAST_NAME LIKE '%s%';

-- 4
SELECT ID, LAST_NAME, FIRST_NAME, START_DATE
FROM S_EMP
WHERE START_DATE > '5-5-1990' AND START_DATE < '26-5-1991';

-- 5
SELECT LAST_NAME, SALARY
FROM S_EMP
WHERE SALARY > 1000 AND SALARY < 2500;

-- 6
SELECT S_EMP.LAST_NAME AS EMPLOYEE_NAME, S_EMP.SALARY AS MONTHLY_SALARY
FROM S_EMP INNER JOIN S_DEPT ON S_EMP.DEPT_ID = S_DEPT.ID
WHERE S_DEPT.ID = 31 OR S_DEPT.ID = 42 OR S_DEPT.ID = 50;

-- 7
SELECT LAST_NAME, START_DATE
FROM S_EMP
WHERE EXTRACT(YEAR FROM START_DATE) = 1991;

-- 8
SELECT S_EMP.ID, S_EMP.LAST_NAME, ROUND(S_EMP.SALARY * 1.5) AS SALARY
FROM S_EMP;

-- 9
SELECT LAST_NAME || '(' || TITLE || ')' AS EMPLOYEES
FROM S_EMP;

-- 10
SELECT NAME
FROM S_PRODUCT
WHERE NAME LIKE '%Ski%';
-- 11
SELECT S_EMP.ID, S_EMP.LAST_NAME, ROUND(MONTHS_BETWEEN(SYSDATE, START_DATE)) AS NUMBERS_MONTHS
FROM S_EMP;
-- 12
SELECT MAX(S_ORD.TOTAL) AS HIGHEST, MIN(S_ORD.TOTAL) AS LOWEST
FROM S_ORD;
-- 13
SELECT S_PRODUCT.ID,S_PRODUCT.NAME, S_ITEM.QUANTITY
FROM S_PRODUCT INNER JOIN S_ITEM ON S_PRODUCT.ID = s_item.item_id
WHERE s_item.ord_id = 101
ORDER BY S_ITEM.QUANTITY;
-- 14
SELECT S_CUSTOMER.ID, S_CUSTOMER.SALES_REP_ID
FROM S_CUSTOMER;
-- 15
SELECT S_CUSTOMER.ID, S_CUSTOMER.NAME, COUNT(S_ORD.ID) AS NUMBERS_OF_ORDERS,S_ORD.ID AS ORDER_NUMBER
FROM S_CUSTOMER LEFT JOIN S_ORD ON S_CUSTOMER.ID = S_ORD.CUSTOMER_ID
GROUP BY S_CUSTOMER.ID, S_CUSTOMER.NAME, S_ORD.ID;
-- 16
SELECT EMP1.ID, EMP1.LAST_NAME, EMP2.LAST_NAME, EMP2.ID AS MANAGER_NUM
FROM S_EMP EMP1 INNER JOIN (
    SELECT * FROM S_EMP
) EMP2 ON EMP1.MANAGER_ID = EMP2.ID;
-- 17
SELECT CUS.ID, ITEM.PRODUCT_ID, ITEM.QUANTITY
FROM S_CUSTOMER CUS, S_ITEM ITEM, S_ORD ORD
WHERE ITEM.ORD_ID = ORD.ID AND ORD.CUSTOMER_ID = CUS.ID
    AND ORD.TOTAL > 100000;
-- 18
SELECT EMP.ID, EMP.FIRST_NAME || EMP.LAST_NAME AS NAME
FROM S_EMP EMP
WHERE EMP.MANAGER_ID IS NULL;
-- 19
SELECT PRO.ID, PRO.NAME
FROM S_PRODUCT PRO
WHERE PRO.NAME LIKE 'Pro%'
ORDER BY PRO.NAME ASC;
-- 20
SELECT PRO.ID, PRO.NAME, PRO.SHORT_DESC
FROM S_PRODUCT PRO
WHERE PRO.SHORT_DESC LIKE '%bicycle%';
-- 21
SELECT COUNT(DISTINCT manager_id) AS number_of_managers
FROM s_emp;
-- 22
SELECT CUS.NAME, CUS.PHONE, COUNT(ORD.ID) AS NUMBERS_ORD
FROM S_CUSTOMER CUS INNER JOIN S_ORD ORD ON CUS.ID = ORD.CUSTOMER_ID
GROUP BY CUS.NAME, CUS.PHONE;
-- 23
SELECT EMP.ID, EMP.FIRST_NAME, EMP.LAST_NAME, EMP.USERID
FROM S_EMP EMP
WHERE EMP.SALARY > (
    SELECT AVG(SALARY)
    FROM S_EMP
);
-- 24
SELECT EMP.ID, EMP.FIRST_NAME, EMP.LAST_NAME, EMP.USERID
FROM S_EMP EMP
WHERE EMP.SALARY > (
    SELECT AVG(SALARY)
    FROM S_EMP
) AND EMP.LAST_NAME LIKE '%t%';
-- 25
SELECT TITLE.TITLE, MAX(EMP.SALARY), MIN(EMP.SALARY), AVG(EMP.SALARY)
FROM S_EMP EMP INNER JOIN S_TITLE TITLE ON EMP.TITLE = TITLE.TITLE
GROUP BY TITLE.TITLE;