CREATE ROLE main_user;
CREATE USER hoangphuc_userdb IDENTIFIED BY 012345678;

CREATE TABLESPACE tbs_01
    DATAFILE '/opt/oracle/oracle_data/lab/lab_2/tbs_f01_1.dbf' SIZE 200M;
//ALTER TABLESPACE TBS_01 ADD DATAFILE '/opt/oracle/oracle_data/lab/lab_2/tbs_f01_2.dbf' SIZE 20M;

GRANT MAIN_USER TO HOANGPHUC_USERDB;
GRANT CREATE SESSION TO HOANGPHUC_USERDB;
GRANT RESOURCE TO HOANGPHUC_USERDB;
ALTER USER HOANGPHUC_USERDB QUOTA 200M ON TBS_01;


ALTER USER HOANGPHUC_USERDB QUOTA UNLIMITED ON TBS_01;
ALTER USER HOANGPHUC_USERDB DEFAULT TABLESPACE TBS_01;

SELECT user, default_tablespace 
FROM user_users;