CREATE DATABASE VIPHAMGIAOTHONG;
USE VIPHAMGIAOTHONG;

CREATE TABLE LOI
(
    MALOI VARCHAR(10) PRIMARY KEY,
    NOIDUNG NVARCHAR(255),
    MUCTIENPHAT DECIMAL(10, 2)
);

CREATE TABLE DOITUONG
(
    MADT VARCHAR(10) PRIMARY KEY,
    HOTEN NVARCHAR(100),
    CMND VARCHAR(20),
    DIACHI NVARCHAR(255),
    BIENKS VARCHAR(20),
    TONGTIENPHAT DECIMAL(15, 2) DEFAULT 0
);

CREATE TABLE VIPHAM
(
    MALOI VARCHAR(10),
    MADT VARCHAR(10),
    THOIDIEMVP DATE,
    NGAYHEN DATE,
    PRIMARY KEY (MALOI, MADT, THOIDIEMVP),
    FOREIGN KEY (MALOI) REFERENCES LOI(MALOI),
    FOREIGN KEY (MADT) REFERENCES DOITUONG(MADT)
);

