-- CREATE PLUGGABLE DATABASE

SELECT status
FROM v$instance;
CREATE PLUGGABLE DATABASE orclpdb3 ADMIN USER hoangphuc_pdb IDENTIFIED BY
012345678 ROLES=
(DBA) file_name_convert=
('pdbseed', 'orclpdb3');
SELECT PDB_NAME, STATUS
FROM cdb_pdbs;

SELECT NAME, OPEN_MODE, RESTRICTED, OPEN_TIME
FROM V$PDBS;

ALTER PLUGGABLE DATABASE orclpdb3
OPEN;

ALTER SESSION
SET CONTAINER
=orclpdb3;

SHOW CON_NAME;

ALTER SESSION
SET CONTAINER
= CDB$ROOT;

SHOW CON_NAME;

ALTER PLUGGABLE DATABASE ORCLPDB3
CLOSE IMMEDIATE;
DROP PLUGGABLE DATABASE ORCLPDB3 INCLUDING DATAFILES;
