-- CREATE PLUGGABLE DATABASE

SELECT status
FROM v$instance;
CREATE PLUGGABLE DATABASE orclpdb2 ADMIN USER hoangphuc_pdb_2 IDENTIFIED BY
012345678 ROLES=
(DBA) file_name_convert=
('pdbseed', 'orclpdb2');
SELECT PDB_NAME, STATUS
FROM cdb_pdbs;

SELECT NAME, OPEN_MODE, RESTRICTED, OPEN_TIME
FROM V$PDBS;

ALTER PLUGGABLE DATABASE orclpdb2
OPEN;

ALTER SESSION
SET CONTAINER
=orclpdb2;

SHOW CON_NAME;

ALTER SESSION
SET CONTAINER
= CDB$ROOT;

SHOW CON_NAME;

ALTER PLUGGABLE DATABASE ORCLPDB1
CLOSE IMMEDIATE;
DROP PLUGGABLE DATABASE ORCLPDB1 INCLUDING DATAFILES;
