CREATE USER hoangphuc_user1 IDENTIFIED BY 112345678;
CREATE USER hoangphuc_user2 IDENTIFIED BY 212345678;
CREATE USER hoangphuc_user3 IDENTIFIED BY 312345678;
CREATE USER hoangphuc_user4 IDENTIFIED BY 412345678;

CREATE TABLESPACE tbs_01
    DATAFILE '/opt/oracle/oracle_data/lab/lab_2/tbs_lab2_ex3.dbf' SIZE 200M;

GRANT CREATE SESSION TO hoangphuc_user1;
GRANT CREATE SESSION TO hoangphuc_user4;

ALTER USER hoangphuc_user1 QUOTA 1M ON TBS_01;
ALTER USER hoangphuc_user2 QUOTA 1M ON TBS_01;
ALTER USER hoangphuc_user3 QUOTA 1M ON TBS_01;
ALTER USER hoangphuc_user4 QUOTA 1M ON TBS_01;

ALTER USER HOANGPHUC_USER3 DEFAULT TABLESPACE TBS_01;


SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'HOANGPHUC_USER1';

CREATE ROLE PROGRAMMING_ROLE;
GRANT CREATE SESSION, CREATE TABLE TO PROGRAMMING_ROLE;

GRANT PROGRAMMING_ROLE TO HOANGPHUC_USER2 WITH ADMIN OPTION;

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'HOANGPHUC_USER2';