-- user 2
CREATE TABLE employees (
    id          NUMBER PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL,
    salary      NUMBER(10,2),
    description VARCHAR2(255)
);
/
GRANT UNLIMITED TABLESPACE TO hoangphuc_user2;
INSERT INTO employees (id, name, salary, description) 
VALUES (1, 'LE NGUYEN HOANG PHUC', 60000, 'BOSS');

INSERT INTO employees (id, name, salary, description) 
VALUES (2, 'NGUYEN HOANG PHUC', 55000, 'Software Engineer');
/

GRANT PROGRAMMING_ROLE TO HOANGPHUC_USER3;
GRANT UPDATE (NAME, SALARY) ON EMPLOYEES TO HOANGPHUC_USER3;

-- user 3
GRANT PROGRAMMING_ROLE TO HOANGPHUC_USER1;
SELECT * FROM HOANGPHUC_USER2.EMPLOYEES;
-- hoangphuc_pdb
GRANT SELECT ON HOANGPHUC_USER2.EMPLOYEES TO HOANGPHUC_USER1;
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'HOANGPHUC_USER3';
GRANT ALL ON HOANGPHUC_USER2.EMPLOYEES TO HOANGPHUC_USER1;
GRANT CREATE SEQUENCE TO HOANGPHUC_USER3;
-- USER 3
CREATE TABLE students (
    id       NUMBER PRIMARY KEY,
    fullname VARCHAR2(100) NOT NULL,
    birthday DATE
);
CREATE SEQUENCE STUDENT_SEQ;
/
CREATE SEQUENCE student_seq 
START WITH 1 
INCREMENT BY 1 
NOCACHE NOCYCLE;

INSERT INTO students (id, fullname, birthday) 
VALUES (student_seq.NEXTVAL, 'LE NGUYEN HOANG PHUC', TO_DATE('2005-05-10', 'YYYY-MM-DD'));

INSERT INTO students (id, fullname, birthday) 
VALUES (student_seq.NEXTVAL, 'NGUYEN HOANG PHUC', TO_DATE('2006-11-22', 'YYYY-MM-DD'));
/
SELECT USERNAME, DEFAULT_TABLESPACE, TEMPORARY_TABLESPACE 
FROM DBA_USERS 
WHERE USERNAME = 'HOANGPHUC_USER3';
ALTER TABLE SYSTEM.STUDENTS TO TBS_01;
GRANT INSERT ON STUDENTS TO HOANGPHUC_USER4;
GRANT DELETE ON STUDENTS TO HOANGPHUC_USER4;