EXEC KIEMTRA_VIPHAM(1, 2025);
/
DECLARE 
    res_TONGSOLOIVP NUMBER;
BEGIN
    TONGSOLOIVP(3, 2025, 'DT10', res_TONGSOLOIVP);
    DBMS_OUTPUT.PUT_LINE(res_TONGSOLOIVP);
END;
/
DECLARE
    SOLUONGVP NUMBER;
BEGIN
    SOLUONGVP := FUNC_TONGSOLOIVP(3, 2025, 'DT02');
    DBMS_OUTPUT.PUT_LINE('TỔNG SỐ LƯỢNG VI PHẠM CỦA ĐỐI TƯỢNG LÀ: ' || SOLUONGVP);
END;
/
